# Mathematical Steps for Clustering Analysis

## 1. Normalized Prices
For each stock i at time t, we normalize the price series using:

P̃ᵢ(t) = (Pᵢ(t) - μᵢ) / σᵢ

Where:
- P̃ᵢ(t) is the normalized price
- Pᵢ(t) is the original price
- μᵢ is the mean price for stock i
- σᵢ is the standard deviation
- μᵢ = (1/T)∑ₜPᵢ(t) where T is total time periods

## 2. Cluster Assignment
For each cluster c, we define the set of stocks in that cluster:

Sₖ = {i : c(i) = k}

Where:
- Sₖ is the set of stocks in cluster k
- c(i) is the cluster assignment for stock i

## 3. Centroid Calculation
For each cluster c, we calculate the centroid series:

P̄ₖ(t) = (1/|Sₖ|)∑ᵢ∈Sₖ P̃ᵢ(t)

Where:
- P̄ₖ(t) is the centroid series for cluster k
- |Sₖ| is the number of stocks in cluster k
- P̃ᵢ(t) are the normalized prices of stocks in cluster k

In [28]:
import pandas as pd
initial_data = pd.read_csv('/Users/dhairya/cs projects/DS303 final project/dataset/stocks_df.csv')
clusters = pd.read_csv('/Users/dhairya/cs projects/DS303 final project/dataset/spectral_clustering_clusters.csv')

In [30]:
clusters['Stock'] = clusters['Stock'].str.replace('_log_return', '')
clusters

           Stock  Cluster
0      20MICRONS        0
1        3MINDIA        2
2         5PAISA        3
3        63MOONS        1
4       A2ZINFRA        1
...          ...      ...
1257  ZODIACLOTH        4
1258        ZOTA        3
1259       ZUARI        0
1260   ZUARIGLOB        0
1261   ZYDUSWELL        3

[1262 rows x 2 columns]

In [31]:
stock_names = clusters['Stock']

In [34]:
closing_price = []
total_stocks = len(stock_names)
processed = 0

for stock in stock_names:
    stock_data = initial_data[initial_data['Stock'] == stock]
    cluster_num = clusters[clusters['Stock'] == stock]['Cluster'].iloc[0]
    price_data = pd.DataFrame({
        'Date': stock_data['Date'], 
        f'{stock}_closing_{cluster_num}': stock_data['Close'],
    })
    price_data = price_data.dropna()
    price_data = price_data.set_index('Date')
    price_data = price_data.loc['2020-01-01':'2022-01-01']
    if not price_data.empty:
        closing_price.append(price_data)
    processed += 1
    remaining = total_stocks - processed
    print(f"Processed {processed}/{total_stocks} stocks. {remaining} stocks remaining.")

Processed 1/1262 stocks. 1261 stocks remaining.
Processed 2/1262 stocks. 1260 stocks remaining.
Processed 3/1262 stocks. 1259 stocks remaining.
Processed 4/1262 stocks. 1258 stocks remaining.
Processed 5/1262 stocks. 1257 stocks remaining.
Processed 6/1262 stocks. 1256 stocks remaining.
Processed 7/1262 stocks. 1255 stocks remaining.
Processed 8/1262 stocks. 1254 stocks remaining.
Processed 9/1262 stocks. 1253 stocks remaining.
Processed 10/1262 stocks. 1252 stocks remaining.
Processed 11/1262 stocks. 1251 stocks remaining.
Processed 12/1262 stocks. 1250 stocks remaining.
Processed 13/1262 stocks. 1249 stocks remaining.
Processed 14/1262 stocks. 1248 stocks remaining.
Processed 15/1262 stocks. 1247 stocks remaining.
Processed 16/1262 stocks. 1246 stocks remaining.
Processed 17/1262 stocks. 1245 stocks remaining.
Processed 18/1262 stocks. 1244 stocks remaining.
Processed 19/1262 stocks. 1243 stocks remaining.
Processed 20/1262 stocks. 1242 stocks remaining.
Processed 21/1262 stocks. 1241 stocks remaining.
Processed 22/1262 stocks. 1240 stocks remaining.
Processed 23/1262 stocks. 1239 stocks remaining.
Processed 24/1262 stocks. 1238 stocks remaining.
Processed 25/1262 stocks. 1237 stocks remaining.
Processed 26/1262 stocks. 1236 stocks remaining.
Processed 27/1262 stocks. 1235 stocks remaining.
Processed 28/1262 stocks. 1234 stocks remaining.
Processed 29/1262 stocks. 1233 stocks remaining.
Processed 30/1262 stocks. 1232 stocks remaining.
Processed 31/1262 stocks. 1231 stocks remaining.
Processed 32/1262 stocks. 1230 stocks remaining.
Processed 33/1262 stocks. 1229 stocks remaining.
Processed 34/1262 stocks. 1228 stocks remaining.
Processed 35/1262 stocks. 1227 stocks remaining.
Processed 36/1262 stocks. 1226 stocks remaining.
Processed 37/1262 stocks. 1225 stocks remaining.
Processed 38/1262 stocks. 1224 stocks remaining.
Processed 39/1262 stocks. 1223 stocks remaining.
Processed 40/1262 stocks. 1222 stocks remaining.
Processed 41/1262 stocks. 1221 stocks remaining.
Processed 42/1262 stocks. 1220 stocks remaining.
Processed 43/1262 stocks. 1219 stocks remaining.
Processed 44/1262 stocks. 1218 stocks remaining.
Processed 45/1262 stocks. 1217 stocks remaining.
Processed 46/1262 stocks. 1216 stocks remaining.
Processed 47/1262 stocks. 1215 stocks remaining.
Processed 48/1262 stocks. 1214 stocks remaining.
Processed 49/1262 stocks. 1213 stocks remaining.
Processed 50/1262 stocks. 1212 stocks remaining.
Processed 51/1262 stocks. 1211 stocks remaining.
Processed 52/1262 stocks. 1210 stocks remaining.
Processed 53/1262 stocks. 1209 stocks remaining.
Processed 54/1262 stocks. 1208 stocks remaining.
Processed 55/1262 stocks. 1207 stocks remaining.
Processed 56/1262 stocks. 1206 stocks remaining.
Processed 57/1262 stocks. 1205 stocks remaining.
Processed 58/1262 stocks. 1204 stocks remaining.
Processed 59/1262 stocks. 1203 stocks remaining.
Processed 60/1262 stocks. 1202 stocks remaining.
Processed 61/1262 stocks. 1201 stocks remaining.
Processed 62/1262 stocks. 1200 stocks remaining.
Processed 63/1262 stocks. 1199 stocks remaining.
Processed 64/1262 stocks. 1198 stocks remaining.
Processed 65/1262 stocks. 1197 stocks remaining.
Processed 66/1262 stocks. 1196 stocks remaining.
Processed 67/1262 stocks. 1195 stocks remaining.
Processed 68/1262 stocks. 1194 stocks remaining.
Processed 69/1262 stocks. 1193 stocks remaining.
Processed 70/1262 stocks. 1192 stocks remaining.
Processed 71/1262 stocks. 1191 stocks remaining.
Processed 72/1262 stocks. 1190 stocks remaining.
Processed 73/1262 stocks. 1189 stocks remaining.
Processed 74/1262 stocks. 1188 stocks remaining.
Processed 75/1262 stocks. 1187 stocks remaining.
Processed 76/1262 stocks. 1186 stocks remaining.
Processed 77/1262 stocks. 1185 stocks remaining.
Processed 78/1262 stocks. 1184 stocks remaining.
Processed 79/1262 stocks. 1183 stocks remaining.
Processed 80/1262 stocks. 1182 stocks remaining.
Processed 81/1262 stocks. 1181 stocks remaining.
Processed 82/1262 stocks. 1180 stocks remaining.
Processed 83/1262 stocks. 1179 stocks remaining.
Processed 84/1262 stocks. 1178 stocks remaining.
Processed 85/1262 stocks. 1177 stocks remaining.
Processed 86/1262 stocks. 1176 stocks remaining.
Processed 87/1262 stocks. 1175 stocks remaining.
Processed 88/1262 stocks. 1174 stocks remaining.
Processed 89/1262 stocks. 1173 stocks remaining.
Processed 90/1262 stocks. 1172 stocks remaining.
Processed 91/1262 stocks. 1171 stocks remaining.
Processed 92/1262 stocks. 1170 stocks remaining.
Processed 93/1262 stocks. 1169 stocks remaining.
Processed 94/1262 stocks. 1168 stocks remaining.
Processed 95/1262 stocks. 1167 stocks remaining.
Processed 96/1262 stocks. 1166 stocks remaining.
Processed 97/1262 stocks. 1165 stocks remaining.
Processed 98/1262 stocks. 1164 stocks remaining.
Processed 99/1262 stocks. 1163 stocks remaining.
Processed 100/1262 stocks. 1162 stocks remaining.
Processed 101/1262 stocks. 1161 stocks remaining.
Processed 102/1262 stocks. 1160 stocks remaining.
Processed 103/1262 stocks. 1159 stocks remaining.
Processed 104/1262 stocks. 1158 stocks remaining.
Processed 105/1262 stocks. 1157 stocks remaining.
Processed 106/1262 stocks. 1156 stocks remaining.
Processed 107/1262 stocks. 1155 stocks remaining.
Processed 108/1262 stocks. 1154 stocks remaining.
Processed 109/1262 stocks. 1153 stocks remaining.
Processed 110/1262 stocks. 1152 stocks remaining.
Processed 111/1262 stocks. 1151 stocks remaining.
Processed 112/1262 stocks. 1150 stocks remaining.
Processed 113/1262 stocks. 1149 stocks remaining.
Processed 114/1262 stocks. 1148 stocks remaining.
Processed 115/1262 stocks. 1147 stocks remaining.
Processed 116/1262 stocks. 1146 stocks remaining.
Processed 117/1262 stocks. 1145 stocks remaining.
Processed 118/1262 stocks. 1144 stocks remaining.
Processed 119/1262 stocks. 1143 stocks remaining.
Processed 120/1262 stocks. 1142 stocks remaining.
Processed 121/1262 stocks. 1141 stocks remaining.
Processed 122/1262 stocks. 1140 stocks remaining.
Processed 123/1262 stocks. 1139 stocks remaining.
Processed 124/1262 stocks. 1138 stocks remaining.
Processed 125/1262 stocks. 1137 stocks remaining.
Processed 126/1262 stocks. 1136 stocks remaining.
Processed 127/1262 stocks. 1135 stocks remaining.
Processed 128/1262 stocks. 1134 stocks remaining.
Processed 129/1262 stocks. 1133 stocks remaining.
Processed 130/1262 stocks. 1132 stocks remaining.
Processed 131/1262 stocks. 1131 stocks remaining.
Processed 132/1262 stocks. 1130 stocks remaining.
Processed 133/1262 stocks. 1129 stocks remaining.
Processed 134/1262 stocks. 1128 stocks remaining.
Processed 135/1262 stocks. 1127 stocks remaining.
Processed 136/1262 stocks. 1126 stocks remaining.
Processed 137/1262 stocks. 1125 stocks remaining.
Processed 138/1262 stocks. 1124 stocks remaining.
Processed 139/1262 stocks. 1123 stocks remaining.
Processed 140/1262 stocks. 1122 stocks remaining.
Processed 141/1262 stocks. 1121 stocks remaining.
Processed 142/1262 stocks. 1120 stocks remaining.
Processed 143/1262 stocks. 1119 stocks remaining.
Processed 144/1262 stocks. 1118 stocks remaining.
Processed 145/1262 stocks. 1117 stocks remaining.
Processed 146/1262 stocks. 1116 stocks remaining.
Processed 147/1262 stocks. 1115 stocks remaining.
Processed 148/1262 stocks. 1114 stocks remaining.
Processed 149/1262 stocks. 1113 stocks remaining.
Processed 150/1262 stocks. 1112 stocks remaining.
Processed 151/1262 stocks. 1111 stocks remaining.
Processed 152/1262 stocks. 1110 stocks remaining.
Processed 153/1262 stocks. 1109 stocks remaining.
Processed 154/1262 stocks. 1108 stocks remaining.
Processed 155/1262 stocks. 1107 stocks remaining.
Processed 156/1262 stocks. 1106 stocks remaining.
Processed 157/1262 stocks. 1105 stocks remaining.
Processed 158/1262 stocks. 1104 stocks remaining.
Processed 159/1262 stocks. 1103 stocks remaining.
Processed 160/1262 stocks. 1102 stocks remaining.
Processed 161/1262 stocks. 1101 stocks remaining.
Processed 162/1262 stocks. 1100 stocks remaining.
Processed 163/1262 stocks. 1099 stocks remaining.
Processed 164/1262 stocks. 1098 stocks remaining.
Processed 165/1262 stocks. 1097 stocks remaining.
Processed 166/1262 stocks. 1096 stocks remaining.
Processed 167/1262 stocks. 1095 stocks remaining.
Processed 168/1262 stocks. 1094 stocks remaining.
Processed 169/1262 stocks. 1093 stocks remaining.
Processed 170/1262 stocks. 1092 stocks remaining.
Processed 171/1262 stocks. 1091 stocks remaining.
Processed 172/1262 stocks. 1090 stocks remaining.
Processed 173/1262 stocks. 1089 stocks remaining.
Processed 174/1262 stocks. 1088 stocks remaining.
Processed 175/1262 stocks. 1087 stocks remaining.
Processed 176/1262 stocks. 1086 stocks remaining.
Processed 177/1262 stocks. 1085 stocks remaining.
Processed 178/1262 stocks. 1084 stocks remaining.
Processed 179/1262 stocks. 1083 stocks remaining.
Processed 180/1262 stocks. 1082 stocks remaining.
Processed 181/1262 stocks. 1081 stocks remaining.
Processed 182/1262 stocks. 1080 stocks remaining.
Processed 183/1262 stocks. 1079 stocks remaining.
Processed 184/1262 stocks. 1078 stocks remaining.
Processed 185/1262 stocks. 1077 stocks remaining.
Processed 186/1262 stocks. 1076 stocks remaining.
Processed 187/1262 stocks. 1075 stocks remaining.
Processed 188/1262 stocks. 1074 stocks remaining.
Processed 189/1262 stocks. 1073 stocks remaining.
Processed 190/1262 stocks. 1072 stocks remaining.
Processed 191/1262 stocks. 1071 stocks remaining.
Processed 192/1262 stocks. 1070 stocks remaining.
Processed 193/1262 stocks. 1069 stocks remaining.
Processed 194/1262 stocks. 1068 stocks remaining.
Processed 195/1262 stocks. 1067 stocks remaining.
Processed 196/1262 stocks. 1066 stocks remaining.
Processed 197/1262 stocks. 1065 stocks remaining.
Processed 198/1262 stocks. 1064 stocks remaining.
Processed 199/1262 stocks. 1063 stocks remaining.
Processed 200/1262 stocks. 1062 stocks remaining.
Processed 201/1262 stocks. 1061 stocks remaining.
Processed 202/1262 stocks. 1060 stocks remaining.
Processed 203/1262 stocks. 1059 stocks remaining.
Processed 204/1262 stocks. 1058 stocks remaining.
Processed 205/1262 stocks. 1057 stocks remaining.
Processed 206/1262 stocks. 1056 stocks remaining.
Processed 207/1262 stocks. 1055 stocks remaining.
Processed 208/1262 stocks. 1054 stocks remaining.
Processed 209/1262 stocks. 1053 stocks remaining.
Processed 210/1262 stocks. 1052 stocks remaining.
Processed 211/1262 stocks. 1051 stocks remaining.
Processed 212/1262 stocks. 1050 stocks remaining.
Processed 213/1262 stocks. 1049 stocks remaining.
Processed 214/1262 stocks. 1048 stocks remaining.
Processed 215/1262 stocks. 1047 stocks remaining.
Processed 216/1262 stocks. 1046 stocks remaining.
Processed 217/1262 stocks. 1045 stocks remaining.
Processed 218/1262 stocks. 1044 stocks remaining.
Processed 219/1262 stocks. 1043 stocks remaining.
Processed 220/1262 stocks. 1042 stocks remaining.
Processed 221/1262 stocks. 1041 stocks remaining.
Processed 222/1262 stocks. 1040 stocks remaining.
Processed 223/1262 stocks. 1039 stocks remaining.
Processed 224/1262 stocks. 1038 stocks remaining.
Processed 225/1262 stocks. 1037 stocks remaining.
Processed 226/1262 stocks. 1036 stocks remaining.
Processed 227/1262 stocks. 1035 stocks remaining.
Processed 228/1262 stocks. 1034 stocks remaining.
Processed 229/1262 stocks. 1033 stocks remaining.
Processed 230/1262 stocks. 1032 stocks remaining.
Processed 231/1262 stocks. 1031 stocks remaining.
Processed 232/1262 stocks. 1030 stocks remaining.
Processed 233/1262 stocks. 1029 stocks remaining.
Processed 234/1262 stocks. 1028 stocks remaining.
Processed 235/1262 stocks. 1027 stocks remaining.
Processed 236/1262 stocks. 1026 stocks remaining.
Processed 237/1262 stocks. 1025 stocks remaining.
Processed 238/1262 stocks. 1024 stocks remaining.
Processed 239/1262 stocks. 1023 stocks remaining.
Processed 240/1262 stocks. 1022 stocks remaining.
Processed 241/1262 stocks. 1021 stocks remaining.
Processed 242/1262 stocks. 1020 stocks remaining.
Processed 243/1262 stocks. 1019 stocks remaining.
Processed 244/1262 stocks. 1018 stocks remaining.
Processed 245/1262 stocks. 1017 stocks remaining.
Processed 246/1262 stocks. 1016 stocks remaining.
Processed 247/1262 stocks. 1015 stocks remaining.
Processed 248/1262 stocks. 1014 stocks remaining.
Processed 249/1262 stocks. 1013 stocks remaining.
Processed 250/1262 stocks. 1012 stocks remaining.
Processed 251/1262 stocks. 1011 stocks remaining.
Processed 252/1262 stocks. 1010 stocks remaining.
Processed 253/1262 stocks. 1009 stocks remaining.
Processed 254/1262 stocks. 1008 stocks remaining.
Processed 255/1262 stocks. 1007 stocks remaining.
Processed 256/1262 stocks. 1006 stocks remaining.
Processed 257/1262 stocks. 1005 stocks remaining.
Processed 258/1262 stocks. 1004 stocks remaining.
Processed 259/1262 stocks. 1003 stocks remaining.
Processed 260/1262 stocks. 1002 stocks remaining.
Processed 261/1262 stocks. 1001 stocks remaining.
Processed 262/1262 stocks. 1000 stocks remaining.
Processed 263/1262 stocks. 999 stocks remaining.
Processed 264/1262 stocks. 998 stocks remaining.
Processed 265/1262 stocks. 997 stocks remaining.
Processed 266/1262 stocks. 996 stocks remaining.
Processed 267/1262 stocks. 995 stocks remaining.
Processed 268/1262 stocks. 994 stocks remaining.
Processed 269/1262 stocks. 993 stocks remaining.
Processed 270/1262 stocks. 992 stocks remaining.
Processed 271/1262 stocks. 991 stocks remaining.
Processed 272/1262 stocks. 990 stocks remaining.
Processed 273/1262 stocks. 989 stocks remaining.
Processed 274/1262 stocks. 988 stocks remaining.
Processed 275/1262 stocks. 987 stocks remaining.
Processed 276/1262 stocks. 986 stocks remaining.
Processed 277/1262 stocks. 985 stocks remaining.
Processed 278/1262 stocks. 984 stocks remaining.
Processed 279/1262 stocks. 983 stocks remaining.
Processed 280/1262 stocks. 982 stocks remaining.
Processed 281/1262 stocks. 981 stocks remaining.
Processed 282/1262 stocks. 980 stocks remaining.
Processed 283/1262 stocks. 979 stocks remaining.
Processed 284/1262 stocks. 978 stocks remaining.
Processed 285/1262 stocks. 977 stocks remaining.
Processed 286/1262 stocks. 976 stocks remaining.
Processed 287/1262 stocks. 975 stocks remaining.
Processed 288/1262 stocks. 974 stocks remaining.
Processed 289/1262 stocks. 973 stocks remaining.
Processed 290/1262 stocks. 972 stocks remaining.
Processed 291/1262 stocks. 971 stocks remaining.
Processed 292/1262 stocks. 970 stocks remaining.
Processed 293/1262 stocks. 969 stocks remaining.
Processed 294/1262 stocks. 968 stocks remaining.
Processed 295/1262 stocks. 967 stocks remaining.
Processed 296/1262 stocks. 966 stocks remaining.
Processed 297/1262 stocks. 965 stocks remaining.
Processed 298/1262 stocks. 964 stocks remaining.
Processed 299/1262 stocks. 963 stocks remaining.
Processed 300/1262 stocks. 962 stocks remaining.
Processed 301/1262 stocks. 961 stocks remaining.
Processed 302/1262 stocks. 960 stocks remaining.
Processed 303/1262 stocks. 959 stocks remaining.
Processed 304/1262 stocks. 958 stocks remaining.
Processed 305/1262 stocks. 957 stocks remaining.
Processed 306/1262 stocks. 956 stocks remaining.
Processed 307/1262 stocks. 955 stocks remaining.
Processed 308/1262 stocks. 954 stocks remaining.
Processed 309/1262 stocks. 953 stocks remaining.
Processed 310/1262 stocks. 952 stocks remaining.
Processed 311/1262 stocks. 951 stocks remaining.
Processed 312/1262 stocks. 950 stocks remaining.
Processed 313/1262 stocks. 949 stocks remaining.
Processed 314/1262 stocks. 948 stocks remaining.
Processed 315/1262 stocks. 947 stocks remaining.
Processed 316/1262 stocks. 946 stocks remaining.
Processed 317/1262 stocks. 945 stocks remaining.
Processed 318/1262 stocks. 944 stocks remaining.
Processed 319/1262 stocks. 943 stocks remaining.
Processed 320/1262 stocks. 942 stocks remaining.
Processed 321/1262 stocks. 941 stocks remaining.
Processed 322/1262 stocks. 940 stocks remaining.
Processed 323/1262 stocks. 939 stocks remaining.
Processed 324/1262 stocks. 938 stocks remaining.
Processed 325/1262 stocks. 937 stocks remaining.
Processed 326/1262 stocks. 936 stocks remaining.
Processed 327/1262 stocks. 935 stocks remaining.
Processed 328/1262 stocks. 934 stocks remaining.
Processed 329/1262 stocks. 933 stocks remaining.
Processed 330/1262 stocks. 932 stocks remaining.
Processed 331/1262 stocks. 931 stocks remaining.
Processed 332/1262 stocks. 930 stocks remaining.
Processed 333/1262 stocks. 929 stocks remaining.
Processed 334/1262 stocks. 928 stocks remaining.
Processed 335/1262 stocks. 927 stocks remaining.
Processed 336/1262 stocks. 926 stocks remaining.
Processed 337/1262 stocks. 925 stocks remaining.
Processed 338/1262 stocks. 924 stocks remaining.
Processed 339/1262 stocks. 923 stocks remaining.
Processed 340/1262 stocks. 922 stocks remaining.
Processed 341/1262 stocks. 921 stocks remaining.
Processed 342/1262 stocks. 920 stocks remaining.
Processed 343/1262 stocks. 919 stocks remaining.
Processed 344/1262 stocks. 918 stocks remaining.
Processed 345/1262 stocks. 917 stocks remaining.
Processed 346/1262 stocks. 916 stocks remaining.
Processed 347/1262 stocks. 915 stocks remaining.
Processed 348/1262 stocks. 914 stocks remaining.
Processed 349/1262 stocks. 913 stocks remaining.
Processed 350/1262 stocks. 912 stocks remaining.
Processed 351/1262 stocks. 911 stocks remaining.
Processed 352/1262 stocks. 910 stocks remaining.
Processed 353/1262 stocks. 909 stocks remaining.
Processed 354/1262 stocks. 908 stocks remaining.
Processed 355/1262 stocks. 907 stocks remaining.
Processed 356/1262 stocks. 906 stocks remaining.
Processed 357/1262 stocks. 905 stocks remaining.
Processed 358/1262 stocks. 904 stocks remaining.
Processed 359/1262 stocks. 903 stocks remaining.
Processed 360/1262 stocks. 902 stocks remaining.
Processed 361/1262 stocks. 901 stocks remaining.
Processed 362/1262 stocks. 900 stocks remaining.
Processed 363/1262 stocks. 899 stocks remaining.
Processed 364/1262 stocks. 898 stocks remaining.
Processed 365/1262 stocks. 897 stocks remaining.
Processed 366/1262 stocks. 896 stocks remaining.
Processed 367/1262 stocks. 895 stocks remaining.
Processed 368/1262 stocks. 894 stocks remaining.
Processed 369/1262 stocks. 893 stocks remaining.
Processed 370/1262 stocks. 892 stocks remaining.
Processed 371/1262 stocks. 891 stocks remaining.
Processed 372/1262 stocks. 890 stocks remaining.
Processed 373/1262 stocks. 889 stocks remaining.
Processed 374/1262 stocks. 888 stocks remaining.
Processed 375/1262 stocks. 887 stocks remaining.
Processed 376/1262 stocks. 886 stocks remaining.
Processed 377/1262 stocks. 885 stocks remaining.
Processed 378/1262 stocks. 884 stocks remaining.
Processed 379/1262 stocks. 883 stocks remaining.
Processed 380/1262 stocks. 882 stocks remaining.
Processed 381/1262 stocks. 881 stocks remaining.
Processed 382/1262 stocks. 880 stocks remaining.
Processed 383/1262 stocks. 879 stocks remaining.
Processed 384/1262 stocks. 878 stocks remaining.
Processed 385/1262 stocks. 877 stocks remaining.
Processed 386/1262 stocks. 876 stocks remaining.
Processed 387/1262 stocks. 875 stocks remaining.
Processed 388/1262 stocks. 874 stocks remaining.
Processed 389/1262 stocks. 873 stocks remaining.
Processed 390/1262 stocks. 872 stocks remaining.
Processed 391/1262 stocks. 871 stocks remaining.
Processed 392/1262 stocks. 870 stocks remaining.
Processed 393/1262 stocks. 869 stocks remaining.
Processed 394/1262 stocks. 868 stocks remaining.
Processed 395/1262 stocks. 867 stocks remaining.
Processed 396/1262 stocks. 866 stocks remaining.
Processed 397/1262 stocks. 865 stocks remaining.
Processed 398/1262 stocks. 864 stocks remaining.
Processed 399/1262 stocks. 863 stocks remaining.
Processed 400/1262 stocks. 862 stocks remaining.
Processed 401/1262 stocks. 861 stocks remaining.
Processed 402/1262 stocks. 860 stocks remaining.
Processed 403/1262 stocks. 859 stocks remaining.
Processed 404/1262 stocks. 858 stocks remaining.
Processed 405/1262 stocks. 857 stocks remaining.

In [37]:
price_data = pd.concat(closing_price, axis=1)
price_data = price_data.dropna(how='any')

In [39]:
price_data.to_csv('/Users/dhairya/cs projects/DS303 final project/dataset/cluster_price_data.csv')

In [41]:
means = price_data.mean()
stds = price_data.std()

normalized_price_data = (price_data - means) / stds
normalized_price_data

,20MICRONS_closing_0,3MINDIA_closing_2,5PAISA_closing_3,63MOONS_closing_1,A2ZINFRA_closing_1,AARTIDRUGS_closing_3,AARVEEDEN_closing_1,AAVAS_closing_2,ABB_closing_2,ABBOTINDIA_closing_3,...,ZEELEARN_closing_1,ZEEMEDIA_closing_1,ZENSARTECH_closing_3,ZENTEC_closing_1,ZODIAC_closing_4,ZODIACLOTH_closing_4,ZOTA_closing_3,ZUARI_closing_0,ZUARIGLOB_closing_0,ZYDUSWELL_closing_3
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,-0.431827,-0.346459,-1.013332,0.849455,3.040884,-1.760085,-0.422339,0.045327,-0.133673,-1.620063,...,2.454495,-0.514574,-0.615272,-0.670237,2.716752,2.716752,-0.155711,-0.643272,-0.643272,-1.037790
2020-01-06,-0.629074,-0.442926,-1.132579,0.619348,2.906427,-1.791253,-0.447838,0.049438,-0.150739,-1.792637,...,2.589542,-0.564254,-0.602385,-0.659390,2.474608,2.474608,-0.199159,-0.562559,-0.562559,-1.145156
2020-01-07,-0.600384,-0.254030,-1.072280,0.753263,3.040884,-1.779070,-0.481838,0.014765,-0.103924,-1.810585,...,2.837128,-0.531134,-0.586374,-0.640407,2.666405,2.666405,-0.193258,-0.243614,-0.243614,-1.173837
2020-01-08,-0.636247,-0.393824,-1.151478,0.670273,2.861608,-1.787962,-0.481838,-0.042873,-0.094561,-1.818096,...,2.657065,-0.531134,-0.587155,-0.653062,2.596879,2.596879,-0.202913,-0.270952,-0.270952,-1.119178
2020-01-09,-0.586039,-0.382520,-1.155528,0.755149,2.816789,-1.772267,-0.456338,0.028259,-0.067539,-1.825390,...,2.544526,-0.547694,-0.579735,-0.612384,2.699969,2.699969,-0.204522,-0.363381,-0.363381,-1.094552
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-27,1.113874,0.839235,0.753324,4.502872,2.771969,-0.090754,2.170123,0.939924,2.002744,1.093491,...,0.091173,1.638245,1.648187,2.187170,-0.462282,-0.462282,2.054729,1.348508,1.348508,0.121612
2021-12-28,1.303949,0.841221,0.754224,4.893299,3.085704,-0.107871,2.416619,0.943231,2.030240,1.216538,...,0.158696,1.836967,1.871565,2.213385,-0.373576,-0.373576,2.077794,1.489104,1.489104,0.304360
2021-12-29,1.293190,0.834816,0.734425,5.302588,3.444257,-0.065188,2.153123,1.051805,2.076462,1.344193,...,0.113681,1.770726,2.073854,2.188978,-0.411935,-0.411935,2.051511,1.554195,1.554195,0.252404
2021-12-30,1.490437,0.866906,0.625527,4.885755,3.802810,-0.092087,1.966126,1.095949,2.097321,1.375531,...,0.451298,1.721046,2.027773,2.212481,-0.363986,-0.363986,2.037565,1.508631,1.508631,0.245947
2021-12-31,1.569336,0.970771,0.715075,5.295043,4.206183,0.006619,2.136124,1.167975,2.093055,1.425297,...,0.743900,1.903207,2.050033,2.199826,-0.270485,-0.270485,2.048829,1.444842,1.444842,0.195642

In [45]:
cluster_cols = {
    k: [col for col in normalized_price_data.columns if col.endswith(f'_{k}')] 
    for k in range(5)
}

centroid_series = {}
spread_series = {}
for k in range(5):
    cluster_data = normalized_price_data[cluster_cols[k]]
    centroid_series[k] = cluster_data.mean(axis=1)
    
    cluster_size = len(cluster_cols[k])
    squared_diffs = (cluster_data.subtract(centroid_series[k], axis=0))**2
    spread = np.sqrt(squared_diffs.sum(axis=1) / cluster_size)
    spread_series[k] = spread

centroid_df = pd.DataFrame({
    f'cluster_{k}_centroid': centroid_series[k]
    for k in range(5)
})

spread_df = pd.DataFrame({
    f'cluster_{k}_spread': spread_series[k]
    for k in range(5)
})

combined_df = pd.concat([centroid_df, spread_df], axis=1)
combined_df

,cluster_0_centroid,cluster_1_centroid,cluster_2_centroid,cluster_3_centroid,cluster_4_centroid,cluster_0_spread,cluster_1_spread,cluster_2_spread,cluster_3_spread,cluster_4_spread
Date,,,,,,,,,,
2020-01-02,-0.356426,-0.307745,-0.074320,-0.820866,0.188381,0.754145,1.191547,0.987925,0.841805,1.085164
2020-01-06,-0.457455,-0.338873,-0.182332,-0.885739,0.094344,0.708825,1.142986,0.929043,0.805300,1.020441
2020-01-07,-0.404615,-0.306742,-0.152079,-0.863048,0.129931,0.726450,1.161624,0.933779,0.824696,1.033595
2020-01-08,-0.412959,-0.319744,-0.154212,-0.866373,0.112394,0.727378,1.147230,0.928599,0.813350,1.019144
2020-01-09,-0.344996,-0.291036,-0.078515,-0.818974,0.193888,0.770532,1.158337,0.959700,0.836273,1.046743
...,...,...,...,...,...,...,...,...,...,...
2021-12-27,1.060850,1.590904,0.936159,0.965559,1.074982,0.697773,1.254619,0.926038,1.002948,0.915668
2021-12-28,1.158257,1.708775,0.992485,1.021547,1.150883,0.697495,1.311364,0.925976,1.000037,0.922528
2021-12-29,1.188209,1.755333,1.000681,1.050173,1.162188,0.713455,1.345387,0.928363,0.994585,0.931087
2021-12-30,1.183620,1.805439,0.994607,1.077520,1.169054,0.705483,1.387094,0.938844,1.031231,0.938034
2021-12-31,1.217719,1.910019,1.049796,1.134849,1.226111,0.704772,1.427969,0.941246,1.035142,0.959144

## Signal Generation

### Cluster Spread (σc):
For each cluster c at time t:

σc(t) = √(1/|Sc| ∑(Pi(t) - P̄c(t))²)

where:
- |Sc| = number of stocks in cluster c
- Pi(t) = normalized price of stock i at time t  
- P̄c(t) = centroid price of cluster c at time t

### Z-Score (zi):
zi(t) = (Pi(t) - P̄c(t))/σc(t)

### Trading Signals:
- zi(t) > 3  → Short stock i
- zi(t) < -3 → Buy stock i 
- -3 ≤ zi(t) ≤ 3 → Hold

In [47]:
z_scores_dict = {}

for k in range(5):
    cluster_stocks = cluster_cols[k]
    centroid = combined_df[f'cluster_{k}_centroid']
    spread = combined_df[f'cluster_{k}_spread']
    
    cluster_z_scores = {}
    for stock in cluster_stocks:
        stock_price = normalized_price_data[stock]
        z_score = (stock_price - centroid) / spread
        cluster_z_scores[stock] = z_score
        
    z_scores_dict.update(cluster_z_scores)

z_scores = pd.DataFrame(z_scores_dict, index=normalized_price_data.index)
z_scores

,20MICRONS_closing_0,ADANIPOWER_closing_0,ALKALI_closing_0,APCL_closing_0,APTECHT_closing_0,ARIES_closing_0,AVADHSUGAR_closing_0,AVTNPL_closing_0,BAJAJHIND_closing_0,BALPHARMA_closing_0,...,VOLTAMP_closing_4,VSSL_closing_4,VTL_closing_4,WABAG_closing_4,WELCORP_closing_4,WONDERLA_closing_4,WSTCSTPAPR_closing_4,YAARI_closing_4,ZODIAC_closing_4,ZODIACLOTH_closing_4
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,-0.099982,0.372624,0.661996,-0.596139,0.145950,-0.630559,0.794963,-0.812958,-0.027243,-0.693419,...,-0.311471,-0.901646,-0.562180,-0.579357,0.381449,1.128042,0.244560,0.117626,2.329943,2.329943
2020-01-06,-0.242118,0.340557,0.770234,-0.572229,0.081508,-0.555955,0.855153,-0.982767,0.040561,-0.684200,...,-0.249975,-0.912678,-0.515543,-0.259796,0.556481,1.233638,0.137225,0.495926,2.332584,2.332584
2020-01-07,-0.269487,0.299613,0.675582,-0.557641,0.034563,-0.609431,0.990377,-0.956241,0.052296,-0.727184,...,-0.217484,-0.893069,-0.559026,-0.297090,0.557362,1.133465,0.172963,0.610698,2.454031,2.454031
2020-01-08,-0.306976,0.259585,0.627106,-0.483589,0.141083,-0.647151,0.967116,-0.963371,-0.021646,-0.730549,...,-0.140764,-0.827319,-0.557149,-0.291490,0.615435,1.237302,0.104396,0.656279,2.437815,2.437815
2020-01-09,-0.312826,0.211393,0.690380,-0.485704,0.266400,-0.582998,0.853573,-0.956455,-0.108637,-0.641419,...,-0.136689,-0.896340,-0.608500,-0.351690,0.794845,1.231678,0.153212,0.723541,2.394170,2.394170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-27,0.075990,-0.006635,0.782411,-0.777223,0.995465,0.300528,0.260371,0.313646,0.089492,0.361021,...,1.590128,0.368416,1.364575,-0.146244,0.397798,-0.896170,-0.510838,-0.982456,-1.678845,-1.678845
2021-12-28,0.208879,-0.074439,0.832965,-0.776842,1.192547,0.279246,0.741133,0.467650,0.157552,0.216033,...,1.568008,0.195700,1.306344,-0.248797,0.443973,-0.848707,-0.482751,-1.038997,-1.652481,-1.652481
2021-12-29,0.147144,-0.166871,0.880232,-0.753976,1.820290,0.068387,0.714899,0.354580,0.083041,0.161182,...,1.575991,0.232172,1.303691,-0.286668,0.462262,-0.979055,-0.494318,-1.064827,-1.690630,-1.690630
2021-12-30,0.434904,-0.180583,0.995817,-0.781637,1.781186,0.248059,0.613243,0.287432,0.017155,0.258907,...,1.613519,0.202722,1.320901,-0.320909,0.379893,-1.006021,-0.595110,-1.087327,-1.634312,-1.634312
2021-12-31,0.498909,-0.217680,0.950656,-0.808428,1.829470,0.134469,0.520632,0.333444,0.115597,0.408744,...,1.402348,0.185779,1.199565,-0.333445,0.331841,-0.959188,-0.512755,-1.097101,-1.560346,-1.560346

In [51]:
z_scores.to_csv('/Users/dhairya/cs projects/DS303 final project/dataset/z_scores.csv')